export const metadata = {
  title: "Installation | Ph - Apps next",
  description: "Generated by create next app",
};

const InstallationPage = () => {
  return (
    <div>
      <h2>This is installation pages</h2>
    </div>
  );
};

export default InstallationPage;
