import TrendingApps from "@/Components/Pages/Home/TrendingApps";

export const metadata = {
  title: "Apps Page | Ph - Apps next",
  description: "Generated by create next app",
};

const AppsPage = () => {
  return (
    <div>
      <TrendingApps from="apps" />
    </div>
  );
};

export default AppsPage;
