export const metadata = {
  title: "Apps Page | Ph - Apps next",
  description: "Generated by create next app",
};

const AppsPage = () => {
  return (
    <div>
      <h2>This is Apps pages</h2>
    </div>
  );
};

export default AppsPage;
